services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  resource-service:
    build:
      context: ./resource-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  song-service:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  pgdata: